language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - git config --global user.email 'redeye217@gmail.com'
  - git config --global user.name 'LatteCom'
  - hexo g -d
